create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  name text not null,
  username text not null unique,
  username_lower text not null unique,
  email text not null,
  account_balance numeric(18, 2) not null default 0,
  total_deposited numeric(18, 2) not null default 0,
  total_withdrawn numeric(18, 2) not null default 0,
  account_status text not null default 'Active',
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  type text not null check (type in ('deposit', 'withdrawal')),
  amount numeric(18, 2) not null check (amount > 0),
  network text not null,
  note text,
  wallet_address text,
  status text not null default 'Pending',
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.profiles enable row level security;
alter table public.transactions enable row level security;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, name, username, username_lower, email)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'name', ''),
    coalesce(new.raw_user_meta_data ->> 'username', split_part(new.email, '@', 1)),
    lower(coalesce(new.raw_user_meta_data ->> 'username', split_part(new.email, '@', 1))),
    new.email
  );

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.username_exists(username_input text)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists(
    select 1
    from public.profiles
    where username_lower = lower(trim(username_input))
  );
$$;

create or replace function public.lookup_login_email(username_input text)
returns text
language sql
security definer
set search_path = public
as $$
  select email
  from public.profiles
  where username_lower = lower(trim(username_input))
  limit 1;
$$;

grant execute on function public.username_exists(text) to anon, authenticated;
grant execute on function public.lookup_login_email(text) to anon, authenticated;

drop policy if exists "profiles select own" on public.profiles;
create policy "profiles select own"
on public.profiles
for select
to authenticated
using ((select auth.uid()) = id);

drop policy if exists "transactions select own" on public.transactions;
create policy "transactions select own"
on public.transactions
for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "transactions insert own" on public.transactions;
create policy "transactions insert own"
on public.transactions
for insert
to authenticated
with check ((select auth.uid()) = user_id);
